name: Deploy Laravel to cPanel via Git Pull
description: This workflow deploys a Laravel application to a cPanel server using SSH and Git pull.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Set up SSH key to connect to the server
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # Step 2: Set up Deploy Key to enable git pull
    - name: Setup Deploy Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # Step 3: Run deployment commands on the cPanel server
    - name: Deploy and Run Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /home/salmanab/dapurtani.salmanabdurrahman.my.id
          
          git pull origin main
          
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          
          npm install
          npm run build
          
          php artisan migrate --force
          
          php artisan filament:optimize
          php artisan filament:optimize-clear
          php artisan optimize:clear
          php artisan optimize
          
          echo "Deployment successful!"