name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup PHP & install dependencies
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: none
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-dev

    # Step 3: Setup Node & build assets
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install NPM dependencies
      run: npm install
    - name: Build assets
      run: npm run build

    # Step 4: Deploy files to cPanel using SCP
    - name: Deploy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "."
        target: "/home/salmanab/dapurtani.salmanabdurrahman.my.id"
        strip_components: 1
        rm: true

    # Step 5: Run commands on the server using SSH
    - name: Run deployment commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /home/salmanab/dapurtani.salmanabdurrahman.my.id
          php artisan optimize:clear
          php artisan optimize
          echo "Deployment successful!"