name: Deploy Laravel to cPanel via Git Pull
description: This workflow deploys the Laravel application to cPanel by pulling the latest changes from the main branch using SSH.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to cPanel
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /home/salmanab/dapurtani.salmanabdurrahman.my.id
          
          echo "Setting up SSH Agent for Git Pull..."
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.DEPLOY_KEY }}")
          
          echo "Pulling latest changes from main branch..."
          git pull origin main
          
          echo "Installing Composer dependencies..."
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          
          echo "Installing NPM dependencies and building assets..."
          npm install
          npm run build
          
          echo "Running database migrations..."
          php artisan migrate --force
          
          echo "Optimizing application..."
          php artisan filament:optimize
          php artisan filament:optimize-clear
          php artisan optimize:clear
          php artisan optimize
          
          echo "Deployment successful!"